### PR TITLE
Added asterisk outbound example

### PR DESCRIPTION
**Pull request by javexed**

### CODE REVIEW

**Comment by benlangfeld** [comment]
IAX is a deprecated technology. It's better here to show an example as `SIP/`, which is far more common and likely to be correct for the reader, and perhaps mention "this may be any Asterisk channel technology, such as SIP, IAX, Skinny, etc.".

**Comment by javexed** [comment]
Done.

**Comment by benlangfeld** [comment]
:+1: @bklang

**Comment by bklang** [comment]
Thanks @javexed! The change is live http://adhearsion.com/docs/console#making-outbound-calls

**Pull request merged**
